name: Makefile CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        token: ${{ secrets.CI_TOKEN }}
        persist-credentials: false # Disable credential persistence

    # Set up Git authentication
    - name: Set up Git authentication
      run: |
        git config --global credential.helper store
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    # Fetch submodules
    - name: Fetch submodules
      run: git submodule update --init --recursive

    # Build the project
    - name: Build project
      run: make
