name: Makefile CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Makefile CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          token: ${{ secrets.ORG_GH_TOKEN }}  # Add this line to pass the token to the checkout action

      - name: Build project
        run: make
